site_name: Projetos e User Stories
site_description: Documentação dos projetos, User Stories e preparativos para os LABs.
docs_dir: 

theme:
  name: material
  palette:
    primary: indigo
    accent: blue

