site_name: Projetos e User Stories
site_description: Documentação dos projetos, User Stories e preparativos para os LABs.
docs_dir: python
theme:
  name: material
  palette:
    primary: indigo
    accent: blue

nav:
  - Início: README.md
  - Documentação de User Stories:
      - Python Essentials 2: python/python-essentials-2/README.md
      