site_name: Solução dos LABs do curso Python Essentials 2
site_description: Documentação e User Stories.
docs_dir: python/python-essentials-2

theme:
  name: material
  palette:
    primary: indigo
    accent: blue

