name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite disparar o processo manualmente pelo painel do GitHub, se necessário

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer o checkout do código
        uses: actions/checkout@v4
        
      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Instalar o MkDocs e dependências
        run: pip install mkdocs-material
        
      - name: Fazer o Deploy no GitHub Pages
        run: mkdocs gh-deploy --force